Vc patient registration
AyurCare-Hospital-Solutions/AyurCare pull request #32
Opened 2024-04-23 17:16 UTC by VikumChathuranga22434

Completed the patient registration feature of the system

2024-04-24 07:54 UTC, yehan2002 commented on backend/routes/PRSS.js
> +router.get("/test-patient", Patient.test);
Remove test api

2024-04-24 14:21 UTC, yehan2002 requested changes

2024-04-24 16:08 UTC, yehan2002 commented on frontend/src/systems/PRS/components/PatientReg/PatientRegForm.tsx
> +      window.location.reload();
Reload page using react-router-dom https://stackoverflow.com/a/61123116/6587830

2024-04-24 18:14 UTC, VikumChathuranga22434 commented on backend/systems/PRSS/patientReg.js
> +async function test(req, res) {
I think i need for some future implementations so after those done I'll remove it

2024-04-24 18:18 UTC, VikumChathuranga22434 commented on backend/systems/PRSS/patientReg.js
> +  const patient = await Patient.findByPk(req.params.id);
I will look in to that

2024-04-24 18:19 UTC, VikumChathuranga22434 commented on backend/systems/PRSS/patientReg.js
> +  const patient = await Patient.findByPk(req.params.id);
Completed that issue

2024-04-24 18:19 UTC, VikumChathuranga22434 commented on frontend/src/systems/PRS/components/PatientReg/MostRecentPatient.tsx
> +      const response = await fetch(`${BASE_URL}/api/prss/recent-patient`);
After all done I'll close this issue @yehan2002

2024-04-24 18:21 UTC, VikumChathuranga22434 commented on frontend/src/systems/PRS/components/PatientReg/PatientRegForm.tsx
> +          <LocalizationProvider dateAdapter={AdapterDayjs}>
This issue yehan We will have a talk. need some information before delete it. And I need to check that this.

2024-04-24 18:23 UTC, VikumChathuranga22434 commented on backend/routes/PRSS.js
> +router.get("/test-patient", Patient.test);
I'll will do that after complete the patient registration. I already completed this feature but i think we need to have some improvement of the code so after looking in to that I'll delete this

2024-04-25 04:44 UTC, yehan2002 commented on frontend/src/systems/PRS/config.ts
Remove this file. Base path is already handled using axios.

2024-04-27 13:59 UTC, yehan2002 approved these changes

2024-04-27 13:59 UTC, merged